#pragma once

#define AIRPDF_COMMUNICATE_PORT 9003

/////////////////////flags/////////////////
#define MSG_FLAG_STREAM_MSG       0x01
#define MSG_FLAG_NOT_USED_0       0x02
#define MSG_FLAG_NOT_USED_1       0x04
#define MSG_FLAG_NOT_USED_2       0x08
#define MSG_FLAG_NOT_USED_3       0x10
#define MSG_FLAG_NOT_USED_4       0x20
#define MSG_FLAG_NOT_USED_5       0x40
#define MSG_FLAG_NOT_USED_6       0x80


#define PAGE_GEN_GRAYSCALE 0x01
#define PAGE_GEN_APLHA     0x02
#define PAGE_GEN_DIS_ACC   0x04


#define PROTOCOL_VERSION (1*255 +1)

#define PROTOCOL_MACHINE_OS_WINDOWS 1
#define PROTOCOL_MACHINE_OS_OSX     2
#define PROTOCOL_MACHINE_OS_IOS     3
#define PROTOCOL_MACHINE_OS_LINUX   4


#define SERVER_FLAGS_ALLOW_REMOTE_ADMIN  0x001
#define SERVER_FLAGS_ALLOW_SET_ROOTS_GUI 0x002
#define SERVER_FLAGS_ALLOW_SET_ROOTS_IOS 0x004
#define SERVER_FLAGS_ALLOW_UPLOADS       0x008
#define SERVER_FLAGS_ALLOW_SHUTDOWN      0x010


/////////////////////MSG ids/////////////////
#define AIRPDF_BROADCAST_MAGIC      0xf0f0f0
#define AIRPDF_MSG_ID_BROADCAST_SRV 1
#define AIRPDF_MSG_ID_BROADCAST_GUI 2
#define AIRPDF_MSG_ID_BROADCAST_IOS 3

#define AIRPDF_MSG_ID_SRV_VERSION 10
#define AIRPDF_MSG_ID_GUI_VERSION 11
#define AIRPDF_MSG_ID_IOS_VERSION 12
#define AIRPDF_MSG_ID_PWD_REQ     18
#define AIRPDF_MSG_ID_PWD         19
#define AIRPDF_MSG_ID_ERROR       20

#define AIRPDF_MSG_ID_REQ_DIR   30
#define AIRPDF_MSG_ID_DIR_FILES 31


#define AIRPDF_MSG_ID_REQ_BOOK_INFO 40
#define AIRPDF_MSG_ID_BOOK_INFO     41
#define AIRPDF_MSG_ID_BOOK_PASS     42
#define AIRPDF_MSG_ID_REQ_BOOK_PAGE 43
#define AIRPDF_MSG_ID_BOOK_PAGE     44
#define AIRPDF_MSG_ID_BOOK_CALC_DPI 45
#define AIRPDF_MSG_ID_BOOK_DPI      46


#define AIRPDF_MSG_ID_SETT_SETTINGS          60
#define AIRPDF_MSG_ID_SETT_ADD_DEL_ROOT_DIR  61
#define AIRPDF_MSG_ID_SETT_ROOT_DIR_LIST     62
#define AIRPDF_MSG_ID_SETT_REQ_MOUNT_POINTS  63
#define AIRPDF_MSG_ID_SETT_MOUNT_POINTS      64

#define AIRPDF_MSG_LAST_MSG        250

